# Generated by Django 5.2.8 on 2026-01-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigoCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=30)),
                ('areaCurso', models.CharField(max_length=30)),
                ('duracionCurso', models.IntegerField()),
                ('cupoMaxCurso', models.IntegerField()),
                ('estadoCurso', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigoSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstudiante', models.CharField(max_length=50)),
                ('documentoEstudiante', models.CharField(max_length=10)),
                ('fechaMatricula', models.DateField()),
                ('cursoMatricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matricula.curso')),
            ],
        ),
    ]
