# Generated by Django 5.2.8 on 2026-01-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='Matricula',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='codigoSolicitud',
            new_name='codigoMatricula',
        ),
    ]
