# Generated by Django 5.2.8 on 2026-01-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0002_rename_solicitud_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('cedulaInstructor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomnreInstructor', models.CharField(max_length=50)),
                ('apellidoInstructor', models.CharField(max_length=50)),
                ('titulacionInstructor', models.CharField(max_length=100)),
                ('fotoInstructor', models.FileField(default='instructor/default.jpg', upload_to='media/instructor/')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='instructorCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Matricula.instructor'),
        ),
    ]
