# Generated by Django 5.2.8 on 2026-01-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0003_instructor_curso_instructorcurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='nomnreInstructor',
            new_name='nombreInstructor',
        ),
    ]
